name: run tests

on:
    push:
        branches: [ master, main ]
    pull_request:
        branches: [ master, main ]

jobs:
    build:
        runs-on: ubuntu-latest
        # runs-on: windows-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 18

            - name: Install dependencies
              run: |
                  npm ci
                  npm install -g mocha
                  npm install chai

            - name: Run tests
              run: |
                  npm run test
